### ISSUE TITLE
Assertation failed in EscPainterAnimatedImages on Windows

### ISSUE THREAD

**Issue by klugier** [ismail-yilmaz/EscPainter#1]
It looks like there is a crash on application opening for EscPainterAnimatedImages on Windows. The error is:
![CrashEscPainterExample](https://user-images.githubusercontent.com/6963025/235501035-95c3a8d8-f131-4858-946c-95e510f15700.png)

**Comment by ismail-yilmaz** [comment]
Thanks!
It was a silly mistake in the animation example file. Now it should be fixed.
Please check.

**Comment by klugier** [comment]
Works fine! Thanks!
